services:
  psql_src:
    build: .
    image: postgres:14.5
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: "checknft"
      POSTGRES_USER: "etl"
      POSTGRES_PASSWORD: "etl_contest"
    volumes:
        - ./pgdump_src:/pgdump_folder
  psql_dst:
    build: .
    image: postgres:14.5
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: "checknft"
      POSTGRES_USER: "etl"
      POSTGRES_PASSWORD: "etl_contest"
    volumes:
        - ./pgdump_dst:/pgdump_folder


